apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-user
  labels:
    app: backend-user
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-user
  template:
    metadata:
      labels:
        app: backend-user
    spec:
      containers:
        - name: backend-user
          image: gbengaps/udagram-api-user:v1
          ports:
            - containerPort: 8080
          env:
            - name: POSTGRES_USERNAME
              valueFrom:
                secretKeyRef:
                  name: env-secret
                  key: POSTGRES_USERNAME
                  optional: false
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: env-secret
                  key: POSTGRES_PASSWORD
                  optional: false
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: env-secret
                  key: JWT_SECRET
                  optional: false
            - name: AWS_PROFILE
              valueFrom:
                secretKeyRef:
                  name: env-secret
                  key: AWS_PROFILE
                  optional: false
            - name: AWS_REGION
              valueFrom:
                secretKeyRef:
                  name: env-secret
                  key: AWS_REGION
                  optional: false
            - name: AWS_BUCKET
              valueFrom:
                secretKeyRef:
                  name: env-secret
                  key: AWS_BUCKET
                  optional: false
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: env-config
                  key: POSTGRES_DB
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  name: env-config
                  key: POSTGRES_HOST
